baseURL = "https://bitbite-io.github.io/home/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "assetbase"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "Platform"
url = "platform"
weight = 2
[[menu.main]]
name = "Pricing"
url = "pricing"
weight = 3
[[menu.main]]
name = "News"
url = "#news"
weight = 4
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 5

# Sitemap Menu
[[menu.sitemap]]
name = "Platform"
url = "platform"
weight = 1
[[menu.sitemap]]
name = "Pricing"
url = "pricing"
weight = 2
[[menu.sitemap]]
name = "Frequently Ask Questions"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 4
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 5

[params]
blogPageURL = "news"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Rådhuset, Vaksalagatan 2, 753 20 Uppsala, Sweden"
email = "sales@bitbite.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+(46) 833 525 32 83"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
[[params.social]]
icon = "fa-github-square"
url = "https://github.com/"
weight = 4
